name: "Build and Release macOS"

# This will trigger the action on each push to the `release` branch.
on:
  workflow_dispatch: # This line enables the manual "Run workflow" button
    inputs:
      environment:
        description: "Environment to run against"
        required: true
        default: "staging"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # Apple Silicon (M1/M2/M3/M4)
            args: "--target aarch64-apple-darwin"
            arch: "aarch64"
          - platform: "macos-latest" # Intel-based Macs
            args: "--target x86_64-apple-darwin"
            arch: "x86_64"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app and create release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # The action automatically replaces __VERSION__ with the version in tauri.conf.json
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-bundles-${{ matrix.arch }}
          path: |
            src-tauri/target/**/bundle/dmg/*.dmg
            src-tauri/target/**/bundle/macos/*.app
          if-no-files-found: warn
